version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
      - dependency-name: dbt-core
        update-types:
          - version-update:semver-minor
      - dependency-name: numpy
        update-types:
          - version-update:semver-minor

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /docker/spark
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: spark
        update-types:
          - version-update:semver-major
