global:
  scrape_interval: 15s

scrape_configs:
  - job_name: kafka
    static_configs:
      - targets: ["kafka-exporter:9308"]

  - job_name: collectors
    static_configs:
      - targets: ["host.docker.internal:8889"]
