status = error
name = CoinWhaleSparkLogConfig

appender.console.type = Console
appender.console.name = console
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n

rootLogger.level = warn
rootLogger.appenderRef.console.ref = console

logger.kafka.name = org.apache.kafka
logger.kafka.level = warn

logger.zookeeper.name = org.apache.zookeeper
logger.zookeeper.level = warn

logger.microbatch.name = org.apache.spark.sql.execution.streaming.MicroBatchExecution
logger.microbatch.level = warn

logger.processing.name = org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor
logger.processing.level = error

logger.resolve.name = org.apache.spark.sql.execution.streaming.ResolveWriteToStream
logger.resolve.level = error

logger.kafkaSource.name = org.apache.spark.sql.kafka010.KafkaSourceProvider
logger.kafkaSource.level = error

logger.nativeCode.name = org.apache.hadoop.util.NativeCodeLoader
logger.nativeCode.level = error
